services:

  app:
    build:
      target: production
    volumes: []

  queue:
    build:
      target: production
    command: ["supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]
    volumes:
      - ./docker/supervisor/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf:ro

  nginx:
    ports:
      - "80:80"
